/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswing;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS TUF
 */
public class FormQTV extends javax.swing.JFrame {

    /**
     * Creates new form FormQTV
     */
    public FormQTV() {
        initComponents();
        try {
                d.readFromFile();
            } catch (IOException ex) {
                Logger.getLogger(FormQTV.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        bTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lTimKiem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lTrong = new javax.swing.JLabel();
        bTimKiem1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lTimKiem1 = new javax.swing.JLabel();
        bTimKiem2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVietNamese = new javax.swing.JTextField();
        bReset = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        lVietNamese = new javax.swing.JLabel();
        lEnglish = new javax.swing.JLabel();
        lHoanTat = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEnglishOld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVietNamese1 = new javax.swing.JTextField();
        bReset1 = new javax.swing.JButton();
        lRepair = new javax.swing.JButton();
        txtEnglishNew = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lEnglishOld = new javax.swing.JLabel();
        lEnglishNew = new javax.swing.JLabel();
        lVietNamese1 = new javax.swing.JLabel();
        lHoanTat1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEnglish1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lHoanTat2 = new javax.swing.JLabel();
        bReset2 = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        bVeTrangTru = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bDangXuat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bTimKiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bTimKiem.setText("Tìm kiếm");
        bTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimKiemActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "English", "VietNamese"
            }
        ));
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);

        lTimKiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nhập \"*\" để hiện thị tất cả");

        lTrong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lTrong.setForeground(new java.awt.Color(255, 0, 51));

        bTimKiem1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bTimKiem1.setText("Reset");
        bTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimKiem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bTimKiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTimKiem))
                .addGap(4, 4, 4)
                .addComponent(lTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTimKiem1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm theo tiền tố", jPanel1);

        txtTimKiem1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "English", "VietNamese"
            }
        ));
        jTable2.setRowHeight(24);
        jScrollPane2.setViewportView(jTable2);

        lTimKiem1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lTimKiem1.setForeground(new java.awt.Color(255, 0, 51));

        bTimKiem2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bTimKiem2.setText("Reset");
        bTimKiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTimKiem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(372, 372, 372)
                            .addComponent(lTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(328, 328, 328)
                            .addComponent(txtTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jButton2))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bTimKiem2)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm một từ", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("English");

        txtEnglish.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("VietNamese");

        txtVietNamese.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bReset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        lVietNamese.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lVietNamese.setForeground(new java.awt.Color(255, 0, 0));

        lEnglish.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lEnglish.setForeground(new java.awt.Color(255, 0, 0));

        lHoanTat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lHoanTat.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(txtVietNamese, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(263, 407, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(415, 415, 415))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lVietNamese, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(416, 416, 416))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVietNamese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lVietNamese, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lHoanTat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReset)
                    .addComponent(bAdd))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm từ", jPanel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("English old");

        txtEnglishOld.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEnglishOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishOldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("VietNamese");

        txtVietNamese1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bReset1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bReset1.setText("Reset");
        bReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReset1ActionPerformed(evt);
            }
        });

        lRepair.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lRepair.setText("Repair");
        lRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lRepairActionPerformed(evt);
            }
        });

        txtEnglishNew.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEnglishNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishNewActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("English new");

        lEnglishOld.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lEnglishOld.setForeground(new java.awt.Color(255, 0, 0));

        lEnglishNew.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lEnglishNew.setForeground(new java.awt.Color(255, 0, 0));

        lVietNamese1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lVietNamese1.setForeground(new java.awt.Color(255, 0, 0));

        lHoanTat1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lHoanTat1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEnglishOld, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(txtVietNamese1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEnglishNew, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lEnglishNew, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(bReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lVietNamese1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(lEnglishOld, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(402, 402, 402))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(lHoanTat1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(410, 410, 410)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnglishOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lEnglishOld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnglishNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lEnglishNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVietNamese1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lVietNamese1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lHoanTat1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReset1)
                    .addComponent(lRepair))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sửa từ", jPanel5);

        txtEnglish1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEnglish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglish1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("English");

        lHoanTat2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lHoanTat2.setForeground(new java.awt.Color(255, 0, 0));

        bReset2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bReset2.setText("Reset");
        bReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReset2ActionPerformed(evt);
            }
        });

        bDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(txtEnglish1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lHoanTat2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(bReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnglish1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lHoanTat2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReset2)
                    .addComponent(bDelete))
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Xoá từ", jPanel4);

        jToolBar1.setRollover(true);

        bVeTrangTru.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bVeTrangTru.setText("Về trang trủ");
        bVeTrangTru.setFocusable(false);
        bVeTrangTru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bVeTrangTru.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bVeTrangTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVeTrangTruActionPerformed(evt);
            }
        });
        jToolBar1.add(bVeTrangTru);
        jToolBar1.add(jSeparator1);

        bDangXuat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bDangXuat.setText("Đăng xuất");
        bDangXuat.setFocusable(false);
        bDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(bDangXuat);
        jToolBar1.add(jSeparator3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static Dictionary d = new Dictionary();
    DefaultTableModel model;
    DefaultTableModel mode2;
    private void bDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDangXuatActionPerformed
        try {                                          
            try {
                // TODO add your handling code here:
                d.saveToFile();
            } catch (IOException ex) {
                Logger.getLogger(FormQTV.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            FormKhach fKhach= new FormKhach();
            fKhach.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FormQTV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDangXuatActionPerformed

    private void bVeTrangTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVeTrangTruActionPerformed
        try {
            // TODO add your handling code here:
            d.saveToFile();
        } catch (IOException ex) {
            Logger.getLogger(FormQTV.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        FormTrangChu fTrangChu= new FormTrangChu();
        fTrangChu.setVisible(true);
    }//GEN-LAST:event_bVeTrangTruActionPerformed

    private void txtEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        txtEnglish.setText("");
        lVietNamese.setText("");
        txtVietNamese.setText("");
        lHoanTat.setText("");
    }//GEN-LAST:event_bResetActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        Word w= new Word(txtEnglish.getText(),txtVietNamese.getText());
        boolean full=true;
        if (w.getEn().equals("")){
            lEnglish.setText("Vui long nhập");
            full=false;
        }
        else {
            lEnglish.setText("");
        }
        if (w.getVn().equals("")){
            lVietNamese.setText("Vui long nhập");
            full=false;
        }
        else {
            lVietNamese.setText("");
        }
        if (full){
            if (d.themTu(w)) {
                lHoanTat.setText("Thêm từ "+w.getEn()+" thành công");
            }
            else {
                lEnglish.setText("Từ đã tồn tại");
            }    
        }
    }//GEN-LAST:event_bAddActionPerformed

    private void txtEnglishOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishOldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishOldActionPerformed

    private void bReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReset1ActionPerformed
        // TODO add your handling code here:
        lEnglishOld.setText("");
        lEnglishNew.setText("");
        lVietNamese1.setText("");
        txtEnglishOld.setText("");
        txtEnglishNew.setText("");
        txtVietNamese1.setText("");
        lHoanTat1.setText("");
    }//GEN-LAST:event_bReset1ActionPerformed

    private void lRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lRepairActionPerformed
        // TODO add your handling code here:
        boolean full=true;
        if (txtEnglishOld.getText().equals("")){
            full= false;
            lEnglishOld.setText("Vui lòng nhập");
        }
        else lEnglishOld.setText("");
        if (txtEnglishNew.getText().equals("")){
            full= false;
            lEnglishNew.setText("Vui lòng nhập");
        }
        else lEnglishNew.setText("");
        if (txtVietNamese1.getText().equals("")){
            full= false;
            lVietNamese1.setText("Vui lòng nhập");
        }
        else lVietNamese1.setText("");
        if (full){
            if (d.findByEnglish(txtEnglishOld.getText())==-1) {
                lEnglishOld.setText("Từ chưa tồn tại");
            }
            else{
                lEnglishOld.setText("");
                if((d.findByEnglish(txtEnglishNew.getText())!=-1) && (lEnglishOld.getText().equalsIgnoreCase(lEnglishNew.getText())==false)){
                    lEnglishNew.setText("Tu da ton tai");
                }
                else{
                    lEnglishNew.setText("");
                    Word w= new Word(txtEnglishNew.getText(),txtVietNamese1.getText());
                    if (lEnglishOld.getText().equalsIgnoreCase(lEnglishNew.getText())) {
                        d.doi(txtEnglishOld.getText(), w);
                    }
                    else {
                        d.remove(d.findByEnglish(txtEnglishOld.getText()));
                        d.themTu(w);
                    }
                    lHoanTat1.setText("Sua thanh cong");
                }
            }
        }
    }//GEN-LAST:event_lRepairActionPerformed

    private void txtEnglishNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishNewActionPerformed

    private void txtEnglish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglish1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglish1ActionPerformed

    private void bReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReset2ActionPerformed
        // TODO add your handling code here:
        lHoanTat2.setText("");
        txtEnglish1.setText("");
    }//GEN-LAST:event_bReset2ActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        if(d.xoaTu(txtEnglish1.getText())){
            lHoanTat2.setText("Xoa thanh cong tu "+txtEnglish1.getText());
        }
        else {
            lHoanTat2.setText("Tu khong ton tai");
        }
    }//GEN-LAST:event_bDeleteActionPerformed
    private char upcase(char c){
        if (c>='a' && c<='z') c-=32;
        return c;
    }
    private boolean laTienTo(String child,String parent){
        if (child.length()>parent.length()) return false;
        else if (child.length()==parent.length()){
            return child.equalsIgnoreCase(parent);
        }
        else {
            for (int i=0; i<child.length(); i++){
                if (upcase(child.charAt(i))!=upcase(parent.charAt(i))) return false;
            }
            return true;
        }
    }
    private void bTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimKiemActionPerformed
        // TODO add your handling code here:
        if (txtTimKiem.getText().equals("")){
            lTrong.setText("Vui long nhap");
        }
        else {
            lTrong.setText("");
            model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            if (txtTimKiem.getText().equals("*")){
                for(int i=0; i< d.getDs().size(); i++){
                    model.addRow(new Object[]{
                        i+1, d.getDs().get(i).getEn(),d.getDs().get(i).getVn()
                    });
                }
            }else{
                boolean tonTai=false;
                for (int i=0; i<d.getDs().size(); i++){
                    if (laTienTo(txtTimKiem.getText(),d.getDs().get(i).getEn())) {
                        tonTai=true;
                        // them vao bang
                        model.addRow(new Object[]{
                            i+1, d.getDs().get(i).getEn(),d.getDs().get(i).getVn()
                        });
                    }
                }
                if(!tonTai) lTimKiem.setText("Khong co tu nao");
                else lTimKiem.setText("");
            }
        }
    }//GEN-LAST:event_bTimKiemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtTimKiem1.getText().equals("")){
            lTimKiem1.setText("Vui long nhap");
        }
        else{
            lTimKiem1.setText("");
            if (d.findByEnglish(txtTimKiem1.getText())==-1){
                lTimKiem1.setText("Tu khong ton tai");
            }
            else{
                lTimKiem1.setText("");
                mode2 = (DefaultTableModel) jTable2.getModel();
                mode2.setRowCount(0);
                int i=d.findByEnglish(txtTimKiem1.getText());
                mode2.addRow(new Object[]{
                            i+1, d.getDs().get(i).getEn(),d.getDs().get(i).getVn()
                        });
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimKiem1ActionPerformed
        // TODO add your handling code here:
        txtTimKiem.setText("");
        lTrong.setText("");
        lTimKiem.setText("");
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_bTimKiem1ActionPerformed

    private void bTimKiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTimKiem2ActionPerformed
        // TODO add your handling code here:
        txtTimKiem1.setText("");
        lTimKiem1.setText("");
        mode2 = (DefaultTableModel) jTable2.getModel();
        mode2.setRowCount(0);
    }//GEN-LAST:event_bTimKiem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormQTV().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDangXuat;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bReset1;
    private javax.swing.JButton bReset2;
    private javax.swing.JButton bTimKiem;
    private javax.swing.JButton bTimKiem1;
    private javax.swing.JButton bTimKiem2;
    private javax.swing.JButton bVeTrangTru;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lEnglish;
    private javax.swing.JLabel lEnglishNew;
    private javax.swing.JLabel lEnglishOld;
    private javax.swing.JLabel lHoanTat;
    private javax.swing.JLabel lHoanTat1;
    private javax.swing.JLabel lHoanTat2;
    private javax.swing.JButton lRepair;
    private javax.swing.JLabel lTimKiem;
    private javax.swing.JLabel lTimKiem1;
    private javax.swing.JLabel lTrong;
    private javax.swing.JLabel lVietNamese;
    private javax.swing.JLabel lVietNamese1;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtEnglish1;
    private javax.swing.JTextField txtEnglishNew;
    private javax.swing.JTextField txtEnglishOld;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiem1;
    private javax.swing.JTextField txtVietNamese;
    private javax.swing.JTextField txtVietNamese1;
    // End of variables declaration//GEN-END:variables
}
